## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

os:
  #- linux
  - osx

notifications:
  email: false

git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: 0.7
  - julia: 1.0
  - julia: nightly


# uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    -
#before_script:
#  - if [ $TRAVIS_OS_NAME = linux ]; then ls; fi
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
# before_install:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - if [ $TRAVIS_OS_NAME = "linux" ]; then
#       bash .travis/amd_sdk.sh;
#       tar -xjf AMD-SDK.tar.bz2;
#       AMDAPPSDK=${HOME}/AMDAPPSDK;
#       export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
#       mkdir -p ${OPENCL_VENDOR_PATH};
#       sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
#       echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
#       export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
#       chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
#       ${AMDAPPSDK}/bin/x86_64/clinfo;
#     fi;

# uncomment the following lines to override the default test script
script:
  - julia --color=yes -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.clone(pwd()); Pkg.build("OpenCL")'
  - julia -e 'using OpenCL'

  - julia --check-bounds=yes --color=yes -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.test("OpenCL")'
  #- julia --check-bounds=yes --color=yes --depwarn=error -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.test("OpenCL")'

  - julia examples/demo.jl
  - julia examples/performance.jl
  - julia examples/hands_on_opencl/ex04/vadd_chain.jl
  - julia examples/hands_on_opencl/ex05/vadd_abc.jl
  - julia examples/hands_on_opencl/ex06/matmul.jl
  - julia examples/hands_on_opencl/ex07/matmul.jl
  - julia examples/hands_on_opencl/ex08/matmul.jl

  # - if [ $TRAVIS_OS_NAME = "linux" ]; then
  #     julia examples/hands_on_opencl/ex09/pi_ocl.jl;
  #   fi;
  # - if [ $TRAVIS_OS_NAME = "linux" ]; then
  #     julia examples/hands_on_opencl/exA/pi_vocl.jl 1;
  #   fi;
  # - if [ $TRAVIS_OS_NAME = "linux" ]; then
  #     julia examples/hands_on_opencl/exA/pi_vocl.jl 4;
  #   fi;
  # - if [ $TRAVIS_OS_NAME = "linux" ]; then
  #     julia examples/hands_on_opencl/exA/pi_vocl.jl 8;
  #   fi;

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
