environment:
  matrix:
  - julia_version: 1.0
  - julia_version: nightly

platform:
  - x64 # 64-bit

# Uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia_version: nightly

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

before_build:
  # old version: http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi
  - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/13794/opencl_runtime_18.1_x64_setup.msi"
  - start /wait msiexec /i opencl_runtime_18.1_x64_setup.msi /qn  /l*v opencl_runtime.log

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia --color=yes examples/demo.jl
  - C:\julia\bin\julia --color=yes examples/performance.jl
  - C:\julia\bin\julia --color=yes examples/hands_on_opencl/ex04/vadd_chain.jl
  - C:\julia\bin\julia --color=yes examples/hands_on_opencl/ex05/vadd_abc.jl
  - C:\julia\bin\julia --color=yes examples/hands_on_opencl/ex06/matmul.jl
  - C:\julia\bin\julia --color=yes examples/hands_on_opencl/ex07/matmul.jl
  - C:\julia\bin\julia --color=yes examples/hands_on_opencl/ex08/matmul.jl
